name: Hola Mundo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  hola:
    runs-on: ubuntu-latest
    
    steps: 
    - name: hola mundo
      run: echo "Hola mundo"

    - name: temporal
      run: echo "Este es un step temporal."
    
    - name: touch file
      run: touch hola.txt
    
    - name: Set Text
      run: echo "Hola mundo" >> hola.txt

    - name: Read File
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: LS
      run: ls -al

