name: "Ejemplo de Composite Actions"

on: [push]

jobs:
    say_hello:
        runs-on: ubuntu-latest

        env:
            MY_VAR: Mi variable de entorno

        steps:
            - name: Test
              run: echo "Valor $MY_VAR"